

CREATE TABLE account
(
    account_number VARCHAR(255) NOT NULL,
    CONSTRAINT account_pkey PRIMARY KEY (account_number)
);

CREATE TABLE expense_limit
(
    amount         numeric(38, 2),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id     VARCHAR(255),
    currency       VARCHAR(255),
    operation_type VARCHAR(255),
    CONSTRAINT expense_limit_pkey PRIMARY KEY (id)
);

CREATE TABLE transaction
(
    limit_exceeded  BOOLEAN,
    amount          numeric(38, 2),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    id              BIGINT NOT NULL,
    account_from_id VARCHAR(255),
    account_to_id   VARCHAR(255),
    currency_code   VARCHAR(255),
    operation_type  VARCHAR(255),
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS expense_limit_id_seq INCREMENT BY 1;
